### ISSUE TITLE
训练reranker一直timeout

### ISSUE THREAD

**Issue by SingL3** [NovaSearch-Team/RAG-Retrieval#112]
config
```yaml
# Model
model_name_or_path: "/var/s3fs/xxx/models/bge-reranker-v2-m3"
model_type: "bert_encoder"
num_labels: 1
query_format: "{}"
document_format: "{}"


## Pointwise Dataset
# train_dataset: "../../../example_data/pointwise_reranker_train_data.jsonl"
# train_dataset_type: "pointwise"
# max_label: 2
# min_label: 0
# max_len: 512
# shuffle_rate: 0.0
# train_label_key: "label"
# val_dataset: "../../../example_data/pointwise_reranker_eval_data.jsonl"
# val_dataset_type: "pointwise"
# val_label_key: "label"
# loss_type: "pointwise_bce"  # "pointwise_bce" or "pointwise_mse"

## Grouped Dataset
train_dataset: "/nfs-153/xxx/data/honghu/train_0703_fixed2/hits_format_all_query_gen.jsonl"
train_dataset_type: "grouped"
train_label_key: "label"
train_group_size: 4
shuffle_rate: 0.0
max_len: 8194
# val_dataset: "/nfs-153/xxx/data/honghu/train_0703_fixed2/hits_format_all_query_gen_val.jsonl"
# val_dataset_type: "grouped"
# val_label_key: "label"
loss_type: "listwise_ce"  # "pairwise_ranknet" or "listwise_ce"


# Training
output_dir: "/var/s3fs/xxx/models/bge-reranker-v2-m3-multisize-8k-RR-0709"

## Model Saving
save_on_epoch_end: 1
num_max_checkpoints: 20

## Hyperparameters
epochs: 20
lr: 5e-5
batch_size: 1
seed: 42
warmup_proportion: 0.1
stable_proportion: 0.0
gradient_accumulation_steps: 10
mixed_precision: fp16

## Logging
log_interval: 1
log_with: "wandb" # "wandb" or "tensorboard"
```

accelerate config
```yaml
compute_environment: LOCAL_MACHINE
distributed_type: FSDP
downcast_bf16: 'no'
fsdp_config:
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_backward_prefetch_policy: BACKWARD_PRE
  fsdp_offload_params: false
  fsdp_sharding_strategy: FULL_SHARD
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: XLMRobertaLayer
  # add
  # fsdp_offload_params: true
  fsdp_cpu_ram_efficient_loading: true
  # fsdp_sync_module_states: true
  # fsdp_use_orig_params: true
  timeout_seconds: 3600
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

启动脚本
```bash
cd /nfs-153/xxx/RAG-Retrieval/

echo $WORLD_SIZE

CURRENT_DATE=$(date "+%Y%m%d%H%M%S")

pip install -r requirements.txt
pip install -e .

ACCELERATE_CONFIG_FILE=../../../config/xlmroberta_default_config.yaml
CONFIG_FILE=config/training_0709.yaml

cd ./rag_retrieval/train/reranker

NUM_PROCESSES=$((WORLD_SIZE * 8))

accelerate launch \
    --config_file ${ACCELERATE_CONFIG_FILE} \
    --num_machines ${WORLD_SIZE} \
    --num_processes ${NUM_PROCESSES} \
    --machine_rank ${NODE_RANK} \
    --main_process_ip ${MASTER_ADDR} \
    --main_process_port 9070 \
    train_reranker.py \
    --config ${CONFIG_FILE} \
    2>&1 | tee ./logs/training_honghu_${CURRENT_DATE}.log
```

频繁timeout，log如下：
```bash
hpc-gpu0233:130:301 [1] NCCL INFO Connected all trees
hpc-gpu0233:129:299 [0] NCCL INFO Connected all trees
hpc-gpu0233:136:298 [7] NCCL INFO Connected all trees
hpc-gpu0233:135:303 [6] NCCL INFO Connected all trees
hpc-gpu0233:131:300 [2] NCCL INFO Connected all trees
hpc-gpu0233:132:305 [3] NCCL INFO Connected all trees
hpc-gpu0233:134:302 [5] NCCL INFO Connected all trees
hpc-gpu0233:133:304 [4] NCCL INFO Connected all trees
Start training for 20 epochs ...

  0%|          | 0/396 [00:00<?, ?it/s][rank2]:[E711 03:08:41.451473499 ProcessGroupNCCL.cpp:603] [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600045 milliseconds before timing out.
[rank2]:[E711 03:08:41.451726206 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 2] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank1]:[E711 03:08:41.462405558 ProcessGroupNCCL.cpp:603] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600054 milliseconds before timing out.
[rank1]:[E711 03:08:41.462691813 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 1] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank5]:[E711 03:08:41.476747255 ProcessGroupNCCL.cpp:603] [Rank 5] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600051 milliseconds before timing out.
[rank5]:[E711 03:08:41.477051557 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 5] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank4]:[E711 03:08:41.480343387 ProcessGroupNCCL.cpp:603] [Rank 4] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600072 milliseconds before timing out.
[rank4]:[E711 03:08:41.480753850 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 4] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank7]:[E711 03:08:41.493188935 ProcessGroupNCCL.cpp:603] [Rank 7] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600034 milliseconds before timing out.
[rank7]:[E711 03:08:41.493490406 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 7] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank6]:[E711 03:08:41.510419478 ProcessGroupNCCL.cpp:603] [Rank 6] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600094 milliseconds before timing out.
[rank6]:[E711 03:08:41.510695037 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 6] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank0]:[E711 03:08:41.521949958 ProcessGroupNCCL.cpp:603] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600086 milliseconds before timing out.
[rank0]:[E711 03:08:41.522274714 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 0] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank3]:[E711 03:08:41.559793428 ProcessGroupNCCL.cpp:603] [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600097 milliseconds before timing out.
[rank3]:[E711 03:08:41.560131419 ProcessGroupNCCL.cpp:1709] [PG 0 (default_pg) Rank 3] Exception (either an error or timeout) detected by watchdog at work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:47 -> 3
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:550 -> 3
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:573 -> 3
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:621 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:47 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:752 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:428 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:564 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:668 -> 3

hpc-gpu0233:131:267 [2] proxy.cc:1458 NCCL WARN [Service thread] Accept failed Resource temporarily unavailable
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:47 -> 3
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:58 -> 3
hpc-gpu0233:131:165 [2] NCCL INFO misc/socket.cc:775 -> 3
hpc-gpu0233:131:267 [2] NCCL INFO misc/socket.cc:826 -> 3

hpc-gpu0233:131:267 [2] proxy.cc:1497 NCCL WARN [Service thread] Could not receive type from localRank 2, res=3, closed=0

hpc-gpu0233:131:267 [2] proxy.cc:1521 NCCL WARN [Proxy Service 2] Failed to execute operation Close from rank 2, retcode 3
hpc-gpu0233:131:165 [2] NCCL INFO comm 0x55c8ee56fe80 rank 2 nranks 16 cudaDev 2 busId 57000 - Abort COMPLETE
[rank2]:[E711 03:08:43.391988331 ProcessGroupNCCL.cpp:1756] [PG 0 (default_pg) Rank 2] Timeout at NCCL work: 36, last enqueued NCCL work: 37, last completed NCCL work: 35.
[rank2]:[E711 03:08:43.392013202 ProcessGroupNCCL.cpp:617] [Rank 2] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[rank2]:[E711 03:08:43.392018389 ProcessGroupNCCL.cpp:623] [Rank 2] To avoid data inconsistency, we are taking the entire process down.
[rank2]:[E711 03:08:43.393836368 ProcessGroupNCCL.cpp:1560] [PG 0 (default_pg) Rank 2] Process group watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600045 milliseconds before timing out.
Exception raised from checkTimeout at /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:605 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f305db2c648 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10a665e (0x7f305ec3b65e in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x2b9 (0x7f305ec46a59 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7f305ec4ff33 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f305ec51d0d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc253 (0x7f30af6b0253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #6: <unknown function> + 0x94ac3 (0x7f30bb6e5ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #7: clone + 0x44 (0x7f30bb776a04 in /usr/lib/x86_64-linux-gnu/libc.so.6)

terminate called after throwing an instance of 'c10::DistBackendError'
  what():  [PG 0 (default_pg) Rank 2] Process group watchdog thread terminated with exception: [Rank 2] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=36, OpType=_ALLGATHER_BASE, NumelIn=787264, NumelOut=12596224, Timeout(ms)=600000) ran for 600045 milliseconds before timing out.
Exception raised from checkTimeout at /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:605 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f305db2c648 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10a665e (0x7f305ec3b65e in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: c10d::ProcessGroupNCCL::WorkNCCL::checkTimeout(std::optional<std::chrono::duration<long, std::ratio<1l, 1000l> > >) + 0x2b9 (0x7f305ec46a59 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: c10d::ProcessGroupNCCL::watchdogHandler() + 0x233 (0x7f305ec4ff33 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #4: c10d::ProcessGroupNCCL::ncclCommWatchdog() + 0x14d (0x7f305ec51d0d in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0xdc253 (0x7f30af6b0253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #6: <unknown function> + 0x94ac3 (0x7f30bb6e5ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #7: clone + 0x44 (0x7f30bb776a04 in /usr/lib/x86_64-linux-gnu/libc.so.6)

Exception raised from ncclCommWatchdog at /opt/pytorch/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1566 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x98 (0x7f305db2c648 in /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x10a665e (0x7f305ec3b65e in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #2: <unknown function> + 0xd48eb4 (0x7f305e8ddeb4 in /usr/local/lib/python3.10/dist-packages/torch/lib/libtorch_cuda.so)
frame #3: <unknown function> + 0xdc253 (0x7f30af6b0253 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #4: <unknown function> + 0x94ac3 (0x7f30bb6e5ac3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #5: clone + 0x44 (0x7f30bb776a04 in /usr/lib/x86_64-linux-gnu/libc.so.6)

W0711 03:08:43.762000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 129 closing signal SIGTERM
W0711 03:08:43.763000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 130 closing signal SIGTERM
W0711 03:08:43.764000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 132 closing signal SIGTERM
W0711 03:08:43.764000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 133 closing signal SIGTERM
W0711 03:08:43.764000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 134 closing signal SIGTERM
W0711 03:08:43.765000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 135 closing signal SIGTERM
W0711 03:08:43.765000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:891] Sending process 136 closing signal SIGTERM
E0711 03:08:44.539000 140498870880064 torch/distributed/elastic/multiprocessing/api.py:863] failed (exitcode: -6) local_rank: 2 (pid: 131) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1093, in launch_command
    multi_gpu_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 734, in multi_gpu_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
====================================================
train_reranker.py FAILED
----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-11_03:08:43
  host      : hpc-gpu0233.kj01.zzjg.dxm-int.com
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 131)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 131
====================================================
```

因为频繁timeout，我在启动脚本增加了以下：
```bash
export NCCL_TIMEOUT_SECONDS=3600
export NCCL_DEBUG=INFO
export TORCH_NCCL_BLOCKING_WAIT=0
```

问题依旧，在代码中做了修改：
```python
from datetime import timedelta
from accelerate.utils import InitProcessGroupKwargs
..........
    accelerator = Accelerator(
        project_config=project_config,
        log_with=args.log_with,
        mixed_precision=args.mixed_precision,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        kwargs_handlers=[InitProcessGroupKwargs(timeout=timedelta(seconds=3600))],
    )
```

硬件为2个节点的A800。

**Comment by NLPJCL** [comment]
注意到你更改了fsdp的config。
如果使用我原始的fsdp config还会出现这个问题吗？

https://github.com/NLPJCL/RAG-Retrieval/blob/master/config/xlmroberta_default_config.yaml

**Comment by SingL3** [comment]
通过
```bash
export NCCL_P2P_DISABLE=1
```
解决了这个问题。
